# Generated by Django 4.1.5 on 2023-01-05 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('power_meter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMetering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_time', models.DateTimeField(default=datetime.datetime.now)),
                ('energy_use', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_metering', to='power_meter.powermeter')),
            ],
        ),
    ]
