# Generated by Django 4.1.5 on 2023-01-05 19:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_metering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energymetering',
            name='energy_use',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
