version: '3.6'
services:
  # Services
  api:
    build:
      context: ./
      target: dev
    image: backend/app
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./app:/home/powermeter/powermeter
    working_dir: /home/powermeter/powermeter
    tty: true
