# Generated by Django 4.1.5 on 2023-01-05 19:16

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9]+$'), 'Enter a valid key.', 'invalid')])),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
